#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FLOW_DOC="$REPO_ROOT/slashCommands/flows/Px-SpecFlow.md"
COMMAND_README="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/README.md"
OPEN_STORY="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_openUserStory.md"
ABORT_STORY="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_abortUserStory.md"
CLEAR_INTENT="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_clearStoryIntent.md"
TAKE_PLAN="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_makePlan.md"
CLOSE_STORY="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_closeUserStory.md"
COMMIT_WORKS="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_commitWorks.md"
UPDATE_ARCH="$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_updateArchDesign.md"
USER_GUIDE="$REPO_ROOT/slashCommands/README_UserGuide.md"

fail() {
  echo "[specflow-take-plan-test] $*" >&2
  exit 1
}

[[ -f "$TAKE_PLAN" ]] || fail "missing SPEC_makePlan command"
[[ -f "$ABORT_STORY" ]] || fail "missing SPEC_abortUserStory command"
[[ -f "$UPDATE_ARCH" ]] || fail "missing SPEC_updateArchDesign command"

grep -Fq '# SPEC_makePlan' "$TAKE_PLAN" || fail "SPEC_makePlan command must declare its heading"
grep -Fq '.catdd/spec/doingUS/*-TASKs.md' "$TAKE_PLAN" || fail "SPEC_makePlan must create a paired TASKs artifact in doingUS"
grep -Fq 'Markdown checkbox tasks: `[ ]` for pending work, `[x]` for satisfied or completed work.' "$TAKE_PLAN" || fail "SPEC_makePlan must require Markdown checkbox task style"
grep -Fq 'print the current TASKs checklist in the command response' "$TAKE_PLAN" || fail "SPEC_makePlan must print TASKs checklist after planning"
grep -Fq 'selected next command should be chosen by lifecycle position and work orientation' "$TAKE_PLAN" || fail "SPEC_makePlan must explain lifecycle-position and work-orientation routing"
grep -Fq 'Distinguish initial design from follow-up design revision' "$TAKE_PLAN" || fail "SPEC_makePlan must distinguish initial design from follow-up design revision"
grep -Fq 'Distinguish requirement-oriented, design-oriented, and implementation-oriented work' "$TAKE_PLAN" || fail "SPEC_makePlan must distinguish requirement, design, and implementation work"
grep -Fq 'follow-up architecture revision' "$TAKE_PLAN" || fail "SPEC_makePlan must allow planning to select follow-up architecture revision"
grep -Fq 'follow-up detail revision' "$TAKE_PLAN" || fail "SPEC_makePlan must allow planning to select follow-up detail revision"

grep -Fq 'Initial next-step recommendation, usually `SPEC_makePlan`.' "$OPEN_STORY" || fail "SPEC_openUserStory must route opened stories to SPEC_makePlan"
grep -Fq 'ask the developer whether to create or switch to a dedicated branch for this story before continuing' "$OPEN_STORY" || fail "SPEC_openUserStory must ask about dedicated branch creation/switch"
grep -Fq '.catdd/spec/abortUS/*-UserStory.md' "$ABORT_STORY" || fail "SPEC_abortUserStory must move stories to abortUS"
grep -Fq 'next recommended command is `SPEC_makePlan`' "$CLEAR_INTENT" || fail "SPEC_clearStoryIntent must hand off to SPEC_makePlan"
grep -Fq '.catdd/spec/doneUS/*-TASKs.md' "$CLOSE_STORY" || fail "SPEC_closeUserStory must preserve the paired TASKs artifact in doneUS"
grep -Fq 'If work used a dedicated story branch and branch integration is still required' "$CLOSE_STORY" || fail "SPEC_closeUserStory must hand off to post-close merge when dedicated branch integration is still required"
grep -Fq 'If merge is already complete or no dedicated story branch was used, report `next_command = no_command` (merge auto-skipped)' "$CLOSE_STORY" || fail "SPEC_closeUserStory must support auto-skipping merge when no dedicated story branch was used"
grep -Fq 'Continue to `SPEC_closeUserStory`.' "$COMMIT_WORKS" || fail "SPEC_commitWorks must continue to close before merge checkpoint"

grep -Fq '[SPEC_makePlan.md](SPEC_makePlan.md)' "$COMMAND_README" || fail "Px-SpecFlow command README must list SPEC_makePlan"
grep -Fq '[SPEC_abortUserStory.md](SPEC_abortUserStory.md)' "$COMMAND_README" || fail "Px-SpecFlow command README must list SPEC_abortUserStory"
grep -Fq 'Create checkbox TASKs and choose the next SPEC step for an opened user story' "$USER_GUIDE" || fail "slashCommands user guide must map the TASKs command"

grep -Fq 'SPEC_makePlan' "$FLOW_DOC" || fail "Px-SpecFlow must include SPEC_makePlan"
grep -Fq '.catdd/spec/doingUS/*-TASKs.md' "$FLOW_DOC" || fail "Px-SpecFlow must document the active TASKs artifact"
grep -Fq '.catdd/spec/abortUS/*-TASKs.md' "$FLOW_DOC" || fail "Px-SpecFlow must document the aborted TASKs artifact"
grep -Fq '.catdd/spec/doneUS/*-TASKs.md' "$FLOW_DOC" || fail "Px-SpecFlow must document the completed TASKs artifact"
grep -Fq '### Part 2.a: Post-Plan Requirement and Design Lanes' "$FLOW_DOC" || fail "Px-SpecFlow must split Part 2.a as requirement/design lifecycle"
grep -Fq '### Part 2.b: Implementation-Oriented Active Story Lifecycle' "$FLOW_DOC" || fail "Px-SpecFlow must split Part 2.b as implementation-oriented lifecycle"
grep -Fq 'PlanChoice -- "design-oriented" --> DesignChoice{"design state?"}' "$FLOW_DOC" || fail "Px-SpecFlow must distinguish design-oriented work after SPEC_makePlan"
grep -Fq 'PlanChoice -- "implementation-oriented" --> Part2b["continue to Part 2.b"]' "$FLOW_DOC" || fail "Px-SpecFlow must hand implementation-oriented work from Part 2.a to Part 2.b"
grep -Fq 'ImplementationChoice{"implementation readiness?"}' "$FLOW_DOC" || fail "Px-SpecFlow must distinguish implementation readiness in Part 2.b"
grep -Fq 'DesignChoice -- "initial arch" --> Arch["SPEC_takeArchDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must route initial architecture design to SPEC_takeArchDesign"
grep -Fq 'DesignChoice -- "follow-up arch" --> UpdateArch["SPEC_updateArchDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must route follow-up architecture design to SPEC_updateArchDesign"
grep -Fq 'DesignChoice -- "initial detail" --> Detail["SPEC_takeDetailDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must route initial detail design to SPEC_takeDetailDesign"
grep -Fq 'DesignChoice -- "follow-up detail" --> UpdateDetail["SPEC_updateDetailDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must route follow-up detail design to SPEC_updateDetailDesign"
grep -Fq 'ImplementationChoice -- "design needs rework" --> ReviewStoryRef["return to Part 2.a SPEC_updateDetailDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must route design-rework implementation state back to detail design"
grep -Fq 'ImplementationChoice -- "story is test-ready" --> DesignTests["SPEC_designUnitTests"]' "$FLOW_DOC" || fail "Px-SpecFlow must allow planning to route implementation-ready work to unit-test design"
grep -Fq 'ImplementationChoice -- "abort" --> Abort2b["SPEC_abortUserStory"]' "$FLOW_DOC" || fail "Px-SpecFlow Part 2.b must support aborting an unsafe active story"
grep -Fq 'QualityDetail -- "YES" --> TailChoice{"after design, what story type?"}' "$FLOW_DOC" || fail "Px-SpecFlow must decide at end of Part 2.a whether to implement or close"
grep -Fq 'TailChoice -- "design-oriented only" --> CommitDesign["SPEC_commitWorks"]' "$FLOW_DOC" || fail "Px-SpecFlow must allow design-only stories to commit without Part 2.b"
grep -Fq 'CommitDesign --> CloseDesign["SPEC_closeUserStory"]' "$FLOW_DOC" || fail "Px-SpecFlow must close design-only stories after commit"
grep -Fq 'optional merge step such as `SPEC_mergeWork` when branch integration is still required' "$FLOW_DOC" || fail "Px-SpecFlow must document optional merge step after close when needed"
grep -Fq 'TailChoice -- "implementation follows" --> DesignReady["handoff to Part 2.b"]' "$FLOW_DOC" || fail "Px-SpecFlow must handoff to Part 2.b when implementation follows"
grep -Fq 'Arch --> ReviewArch["SPEC_reviewArchDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must always review architecture after take"
grep -Fq 'QualityArch -- "NO" --> UpdateArch["SPEC_updateArchDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must route failed architecture review to SPEC_updateArchDesign"
grep -Fq 'UpdateArch --> ReviewArch' "$FLOW_DOC" || fail "Px-SpecFlow must always review architecture after update"
grep -Fq 'Detail --> ReviewDetail["SPEC_reviewDetailDesign"]' "$FLOW_DOC" || fail "Px-SpecFlow must always review detail design after take"
grep -Fq 'UpdateDetail --> ReviewDetail' "$FLOW_DOC" || fail "Px-SpecFlow must always review detail design after update"
grep -Fq 'Abort2a --> AbortUS2a[".catdd/spec/abortUS/*-UserStory.md"]' "$FLOW_DOC" || fail "Px-SpecFlow Part 2.a must move aborted stories to abortUS"
grep -Fq 'Abort2b --> AbortUS2b[".catdd/spec/abortUS/*-UserStory.md"]' "$FLOW_DOC" || fail "Px-SpecFlow Part 2.b must move aborted stories to abortUS"

grep -Fq 'Route to `SPEC_reviewDetailDesign` first.' "$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_takeDetailDesign.md" || fail "SPEC_takeDetailDesign must route to SPEC_reviewDetailDesign"
grep -Fq 'Route to `SPEC_reviewArchDesign` next.' "$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_takeArchDesign.md" || fail "SPEC_takeArchDesign must route to SPEC_reviewArchDesign"
grep -Fq 'Next recommended command after any update is `SPEC_reviewDetailDesign`' "$REPO_ROOT/slashCommands/commands/Px-SpecFlow/SPEC_updateDetailDesign.md" || fail "SPEC_updateDetailDesign must route to SPEC_reviewDetailDesign"
grep -Fq 'Next recommended command after any update is `SPEC_reviewArchDesign`' "$UPDATE_ARCH" || fail "SPEC_updateArchDesign must route to SPEC_reviewArchDesign"

echo "[specflow-take-plan-test] PASSED: SPEC_makePlan is wired into SpecFlow"
